#define vector_compute_time rvv_binary_vector_compute_time
#define vector_int8_matmul rvv_binary_vector_int8_matmul
#define vector_int8_matmul_with_opts rvv_binary_vector_int8_matmul_with_opts
#define vector_int8_set_default_mode rvv_binary_vector_set_default_mode
#define vector_int8_get_default_mode rvv_binary_vector_get_default_mode
#define vector_int8_get_last_estimated_total_cycles rvv_binary_vector_get_last_estimated_total_cycles
#define vector_int8_get_last_estimated_compute_cycles rvv_binary_vector_get_last_estimated_compute_cycles
#define matmul_vec_slice_init rvv_binary_matmul_vec_slice_init
#define matmul_vec rvv_binary_matmul_vec

#include "../rvv_binary/kernel/vector.c"
