#ifndef MYTEST_DATA_DECLS_H
#define MYTEST_DATA_DECLS_H

DECLARE_KERNEL_DATA(case1)
DECLARE_KERNEL_DATA(case2)
DECLARE_KERNEL_DATA(case3)
DECLARE_KERNEL_DATA(case4)
DECLARE_KERNEL_DATA(case5)
DECLARE_KERNEL_DATA(case6)
DECLARE_KERNEL_DATA(case7)
DECLARE_KERNEL_DATA(case8)

#endif
