#ifndef MYTEST_DATA_DECLS_H
#define MYTEST_DATA_DECLS_H

DECLARE_KERNEL_DATA(case_binary)
#define HAS_KERNEL_DATA_CASE_BINARY 1
DECLARE_KERNEL_DATA(case_int2)
#define HAS_KERNEL_DATA_CASE_INT2 1
DECLARE_KERNEL_DATA(case_int4)
#define HAS_KERNEL_DATA_CASE_INT4 1

#endif
