#ifndef BMPMM_DATA_DECLS_H
#define BMPMM_DATA_DECLS_H

DECLARE_KERNEL_DATA_SQUARE(64)
#define HAS_KERNEL_DATA_SQUARE_64 1

DECLARE_KERNEL_DATA(case1)
#define HAS_KERNEL_DATA_CASE1 1
DECLARE_KERNEL_DATA(case2)
#define HAS_KERNEL_DATA_CASE2 1
DECLARE_KERNEL_DATA(case3)
#define HAS_KERNEL_DATA_CASE3 1
DECLARE_KERNEL_DATA(case4)
#define HAS_KERNEL_DATA_CASE4 1

#endif
