#ifndef MYTEST_DATA_DECLS_H
#define MYTEST_DATA_DECLS_H

DECLARE_KERNEL_DATA(case1)
DECLARE_KERNEL_DATA(case2)
DECLARE_KERNEL_DATA(case3)
DECLARE_KERNEL_DATA(case4)
DECLARE_KERNEL_DATA(case5)
DECLARE_KERNEL_DATA(case6)
DECLARE_KERNEL_DATA(case7)
DECLARE_KERNEL_DATA(case8)
DECLARE_KERNEL_DATA(case9)
DECLARE_KERNEL_DATA(case10)
DECLARE_KERNEL_DATA(case11)
DECLARE_KERNEL_DATA(case12)
DECLARE_KERNEL_DATA(case13)
DECLARE_KERNEL_DATA(case14)
DECLARE_KERNEL_DATA(case15)
DECLARE_KERNEL_DATA(case16)
DECLARE_KERNEL_DATA(case17)
DECLARE_KERNEL_DATA(case18)

#endif
