#!/usr/bin/env python3
"""Generate BMP configuration dispatch stubs and lookup table.

The dispatch layer emits one tiny stub per supported `bmpcfg` immediate so the
runtime can binary-search a table and call the matching stub. The supported
tuple space follows the software path limits encoded in this repository:

- prec in {0, 1, 2, 3}
- ktile in {8, 16, ..., 256}, capped by activation/weight bank capacity
- mtile in {8, 16, ..., 64}
- ntile in {16, 32, ..., 128}
- gm, gn in [1, 8], subject to the working-set capacity cap `gm * gn <= g_cap`
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent
STUBS_PATH = ROOT / "bmpcfg_dispatch_stubs.S"
TABLE_PATH = ROOT / "bmpcfg_dispatch_table.inc"

PRECS = (
    (0, 1),
    (1, 2),
    (2, 2),
    (3, 4),
)
K_TILE_MAX = 256
M_VALUES = range(8, 65, 8)
N_VALUES = range(16, 129, 16)
GROUP_DIM_MAX = 8
BUFFER_AREA_ELEMS = 1024
ACT_BANK_CAP_BITS = 8192
WGT_BANK_CAP_BITS = 8192
ACT_BITS = 8


@dataclass(frozen=True, order=True)
class BmpcfgTuple:
    prec: int
    ktile: int
    mtile: int
    ntile: int
    gm: int
    gn: int

    def pack_imm25(self) -> int:
        return (
            (self.prec << 22)
            | (((self.ktile >> 3) - 1) << 17)
            # Keep the existing 4-row-spaced field encoding, but only emit the
            # even codes corresponding to 8-row executable mtile values.
            | (((self.mtile - 8) >> 2) << 13)
            | (((self.ntile - 16) >> 4) << 10)
            | ((self.gm - 1) << 7)
            | ((self.gn - 1) << 4)
        )


def align_down(value: int, step: int) -> int:
    return value - (value % step)


def iter_supported_tuples() -> list[BmpcfgTuple]:
    out: list[BmpcfgTuple] = []
    for prec, weight_bits in PRECS:
        for mtile in M_VALUES:
            act_k_cap = ACT_BANK_CAP_BITS // (mtile * ACT_BITS)
            for ntile in N_VALUES:
                g_cap = BUFFER_AREA_ELEMS // (mtile * ntile)
                if g_cap < 1:
                    continue

                wgt_k_cap = WGT_BANK_CAP_BITS // (ntile * weight_bits)
                ktile_cap = align_down(min(K_TILE_MAX, act_k_cap, wgt_k_cap), 8)
                if ktile_cap < 8:
                    continue

                for ktile in range(8, ktile_cap + 1, 8):
                    for gm in range(1, GROUP_DIM_MAX + 1):
                        for gn in range(1, GROUP_DIM_MAX + 1):
                            if gm * gn > g_cap:
                                continue
                            out.append(BmpcfgTuple(prec, ktile, mtile, ntile, gm, gn))
    return out


def render_stubs(tuples: list[BmpcfgTuple]) -> str:
    lines = [
        "# Auto-generated by src/apps/common/gen_bmpcfg_dispatch.py. Do not edit by hand.",
        ".text",
        "",
    ]
    for idx, cfg in enumerate(tuples):
        stub = f"bmpcfg_emit_stub_{idx:04d}"
        lines.extend(
            [
                f".globl {stub}",
                ".p2align 2",
                f".type {stub}, @function",
                f"{stub}:",
                f"    bmpcfg {cfg.prec}, {cfg.ktile}, {cfg.mtile}, {cfg.ntile}, {cfg.gm}, {cfg.gn}",
                "    ret",
                f".size {stub}, .-{stub}",
                "",
            ]
        )
    return "\n".join(lines)


def render_table(tuples: list[BmpcfgTuple]) -> str:
    lines = [
        "/* Auto-generated by src/apps/common/gen_bmpcfg_dispatch.py. Do not edit by hand. */",
    ]
    for idx, _cfg in enumerate(tuples):
        lines.append(f"extern void bmpcfg_emit_stub_{idx:04d}(void);")
    lines.extend(
        [
            "",
            "static const bmpcfg_dispatch_entry_t bmpcfg_dispatch_table[] = {",
        ]
    )
    for idx, cfg in enumerate(tuples):
        lines.append(f"    {{0x{cfg.pack_imm25():07X}u, bmpcfg_emit_stub_{idx:04d}}},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    tuples = sorted(iter_supported_tuples(), key=lambda cfg: cfg.pack_imm25())
    STUBS_PATH.write_text(render_stubs(tuples))
    TABLE_PATH.write_text(render_table(tuples))
    print(f"generated {len(tuples)} bmpcfg tuples")


if __name__ == "__main__":
    main()
