#ifndef _BMPMM_DATA_DECLS_H_
#define _BMPMM_DATA_DECLS_H_

/*
 * Central place to declare which pre-generated data blobs should be
 * referenced by the C sources.  By editing this file you control which
 * extern symbols are declared and which branches inside get_kernel_data()
 * are compiled into the binary.
 *
 * Usage: uncomment or add the `DECLARE_*` lines for the datasets you want
 * to compile in, and keep the rest commented out to save memory / binary
 * size. For each `DECLARE_KERNEL_DATA_SQUARE(<s>)` also define the
 * corresponding `HAS_KERNEL_DATA_SQUARE_<s>` so `data.c` will include the
 * matching `case`.
 */

/* Current validation scope: enable only one representative shape (64x64). */
// DECLARE_KERNEL_DATA_SQUARE(16)
// #define HAS_KERNEL_DATA_SQUARE_16 1
// DECLARE_KERNEL_DATA_SQUARE(32)
// #define HAS_KERNEL_DATA_SQUARE_32 1
DECLARE_KERNEL_DATA_SQUARE(64)
#define HAS_KERNEL_DATA_SQUARE_64 1
// DECLARE_KERNEL_DATA_SQUARE(128)
// #define HAS_KERNEL_DATA_SQUARE_128 1
// DECLARE_KERNEL_DATA_SQUARE(256)
// #define HAS_KERNEL_DATA_SQUARE_256 1
// DECLARE_KERNEL_DATA_SQUARE(512)
// #define HAS_KERNEL_DATA_SQUARE_512 1
// DECLARE_KERNEL_DATA_SQUARE(1024)
// #define HAS_KERNEL_DATA_SQUARE_1024 1
// DECLARE_KERNEL_DATA_SQUARE(2048)
// #define HAS_KERNEL_DATA_SQUARE_2048 1
// DECLARE_KERNEL_DATA_SQUARE(4096)
// #define HAS_KERNEL_DATA_SQUARE_4096 1

DECLARE_KERNEL_DATA(case1)
#define HAS_KERNEL_DATA_CASE1 1
DECLARE_KERNEL_DATA(case2)
#define HAS_KERNEL_DATA_CASE2 1
DECLARE_KERNEL_DATA(case3)
#define HAS_KERNEL_DATA_CASE3 1
DECLARE_KERNEL_DATA(case4)
#define HAS_KERNEL_DATA_CASE4 1
DECLARE_KERNEL_DATA(case5)
#define HAS_KERNEL_DATA_CASE5 1
DECLARE_KERNEL_DATA(case6)
#define HAS_KERNEL_DATA_CASE6 1
DECLARE_KERNEL_DATA(case7)
#define HAS_KERNEL_DATA_CASE7 1
DECLARE_KERNEL_DATA(case8)
#define HAS_KERNEL_DATA_CASE8 1
DECLARE_KERNEL_DATA(case9)
#define HAS_KERNEL_DATA_CASE9 1
DECLARE_KERNEL_DATA(case10)
#define HAS_KERNEL_DATA_CASE10 1
DECLARE_KERNEL_DATA(case11)
#define HAS_KERNEL_DATA_CASE11 1
DECLARE_KERNEL_DATA(case12)
#define HAS_KERNEL_DATA_CASE12 1
DECLARE_KERNEL_DATA(case13)
#define HAS_KERNEL_DATA_CASE13 1
DECLARE_KERNEL_DATA(case14)
#define HAS_KERNEL_DATA_CASE14 1
DECLARE_KERNEL_DATA(case15)
#define HAS_KERNEL_DATA_CASE15 1
DECLARE_KERNEL_DATA(case16)
#define HAS_KERNEL_DATA_CASE16 1
DECLARE_KERNEL_DATA(case17)
#define HAS_KERNEL_DATA_CASE17 1
DECLARE_KERNEL_DATA(case18)
#define HAS_KERNEL_DATA_CASE18 1
DECLARE_KERNEL_DATA(case19)
#define HAS_KERNEL_DATA_CASE19 1
DECLARE_KERNEL_DATA(case20)
#define HAS_KERNEL_DATA_CASE20 1
DECLARE_KERNEL_DATA(case21)
#define HAS_KERNEL_DATA_CASE21 1
DECLARE_KERNEL_DATA(case22)
#define HAS_KERNEL_DATA_CASE22 1
DECLARE_KERNEL_DATA(case23)
#define HAS_KERNEL_DATA_CASE23 1
DECLARE_KERNEL_DATA(case24)
#define HAS_KERNEL_DATA_CASE24 1
DECLARE_KERNEL_DATA(case25)
#define HAS_KERNEL_DATA_CASE25 1
DECLARE_KERNEL_DATA(case26)
#define HAS_KERNEL_DATA_CASE26 1
DECLARE_KERNEL_DATA(case27)
#define HAS_KERNEL_DATA_CASE27 1
DECLARE_KERNEL_DATA(case28)
#define HAS_KERNEL_DATA_CASE28 1
DECLARE_KERNEL_DATA(case29)
#define HAS_KERNEL_DATA_CASE29 1
DECLARE_KERNEL_DATA(case30)
#define HAS_KERNEL_DATA_CASE30 1
DECLARE_KERNEL_DATA(case31)
#define HAS_KERNEL_DATA_CASE31 1
DECLARE_KERNEL_DATA(case32)
#define HAS_KERNEL_DATA_CASE32 1
DECLARE_KERNEL_DATA(case33)
#define HAS_KERNEL_DATA_CASE33 1
DECLARE_KERNEL_DATA(case34)
#define HAS_KERNEL_DATA_CASE34 1

#endif /* _BMPMM_DATA_DECLS_H_ */
